INSERT INTO marque (nom) VALUES
-- Marques belges initiales
('Côte d\'Or'),
('Delhaize'),
('Chocolaterie Neuhaus'),
('Leonidas'),
('Godiva'),
('Lutosa'),
('Jupiler'),
('Chimay'),
('Rochefort'),
('Duvel'),
('Stella Artois'),
('Guylian'),
('Galler'),
('Bel'),
('Maredsous'),
('Orval'),
('Speculoos'),
('Westmalle'),
('Affligem'),
('Corné Port-Royal'),

-- Marques françaises initiales
('Danone'),
('Bonne Maman'),
('Lactel'),
('Evian'),
('Badoit'),
('Yoplait'),
('Nestlé France'),
('Lindt France'),
('Kinder France'),
('La Laitière'),
('Lu'),
('Charal'),
('Herta'),
('Tropicana'),
('Milka'),
('Suchard'),
('Vittel'),
('Volvic'),
('Blédina'),
('Amora');
